### ISSUE TITLE
Cannot create page

### ISSUE THREAD

**Issue by hohokibeza** [python273/telegraph#11]
I cannot create pages. I'm running the sample code and here's what's happening:
```
File "AutoContent.py", line 6, in <module>
    html_content='<p>Hello, world!</p>'
  File "C:\Program Files\Python36\lib\site-packages\telegraph\api.py", line 168, in create_page
    'return_content': return_content
  File "C:\Program Files\Python36\lib\site-packages\telegraph\api.py", line 40, in method
    raise TelegraphException(response.get('error'))
telegraph.exceptions.TelegraphException: PAGE_SAVE_FAILED
```

**Comment by eamag** [comment]
Cannot reproduce this problem, could you give us more information?

**Comment by python273** [comment]
The server returns this error sometimes. I'm not sure what's the reason

**Comment by PheyMark** [comment]
Traceback (most recent call last):
  File "f.py", line 9, in <module>
    html_content='<p>Hello, world!</p>'
  File "/usr/local/lib/python2.7/dist-packages/telegraph/api.py", line 165, in create_page
    'return_content': return_content
  File "/usr/local/lib/python2.7/dist-packages/telegraph/api.py", line 37, in method
    raise TelegraphException(response.get('error'))
telegraph.exceptions.TelegraphException: PAGE_SAVE_FAILED
