### ISSUE TITLE
How to upload file?

### ISSUE THREAD

**Issue by ZeroFox20** [python273/telegraph#60]
I can't fix this error. Please help.
My Code:
```
from telegraph import Telegraph

telegraph = Telegraph()
telegraph.create_account(short_name='1337')

file = telegraph.upload_file('file.png')
```

Error:
```
Traceback (most recent call last):
  File "d:\Visual Studio Code Projects\Telegraph\test.py", line 6, in <module>
    file = telegraph.upload_file('file.png')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langugages\Python\3.12.6\Lib\site-packages\telegraph\api.py", line 271, in upload_file
    return self._telegraph.upload_file(f)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Langugages\Python\3.12.6\Lib\site-packages\telegraph\api.py", line 64, in upload_file
    error = response.get('error')
            ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by mercuree** [comment]
`d:\Visual Studio Code Projects\Telegraph\test.py`
I would recommend you rename Telegraph folder to something else.

**Comment by python273** [comment]
File uploading is disabled, you'll need to upload files somewhere else
